// <auto-generated/>
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitleAttribute("SimpleSpeedTester")]
[assembly: AssemblyProductAttribute("SimpleSpeedTester")]
[assembly: AssemblyDescriptionAttribute("A simple framework to help benchmark test your .Net code.")]
[assembly: AssemblyVersionAttribute("1.1.0")]
[assembly: AssemblyFileVersionAttribute("1.1.0")]
[assembly: InternalsVisibleToAttribute("SimpleSpeedTester.Tests")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.1.0";
    }
}
